[package]
name = "dinotreedemo"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
edition = "2018"


[dependencies]
axgeom ="*"
ordered-float ="*"
dists = "*"
dinotree = "*"
dinotree_alg="*"
duckduckgeo="*"
